export const POSTGRES_REPOSITORIES = {
    USER_REPOSITORY: 'USER_REPOSITORY',
    TASK_REPOSITORY: 'TASK_REPOSITORY',
}

export const SYSTEM_DATASOURCES = {
    POSTGRES_DATASOURCE: 'POSTGRES_DATASOURCE',
}